export const COMMUNITY_GROUP_ONBOARDING = {
    badge: 'New',
    title: 'Community Group Chats',
    subtitle: 'Gather local people around shared interests and local activities.',
    cta: 'Create a Group',
    features: [
        {
            icon: 'link-outline' as const,
            title: 'Easy Invite Links',
            body: 'Share direct invite links across Gazetteer or post them anywhere.',
        },
        {
            icon: 'people-outline' as const,
            title: 'Interest & Local Hubs',
            body: 'Connect local sports teams, running clubs, book groups, or neighbors.',
        },
        {
            icon: 'shield-checkmark-outline' as const,
            title: 'Group Admin Controls',
            body: 'Manage members, moderate discussions, and keep your space safe.',
        },
    ],
    bubbles: [
        {
            id: 'run',
            name: 'Aoife',
            initials: 'A',
            avatarColor: '#1d4ed8',
            text: 'Saturday 5k at the park gates — who’s in?',
            reaction: '🏃',
            reactionCount: 3,
            align: 'left' as const,
        },
        {
            id: 'reply',
            name: '',
            initials: '',
            avatarColor: '',
            text: 'I’ll be there',
            reaction: '',
            reactionCount: 0,
            align: 'right' as const,
        },
        {
            id: 'match',
            name: 'Declan',
            initials: 'D',
            avatarColor: '#0f766e',
            text: 'Match updates live in this chat ⚽',
            reaction: '⚽',
            reactionCount: 2,
            align: 'left' as const,
        },
        {
            id: 'books',
            name: 'Maeve',
            initials: 'M',
            avatarColor: '#7c3aed',
            text: 'Book club Thursday at the library',
            reaction: '📚',
            reactionCount: 2,
            align: 'left' as const,
        },
    ],
} as const;
