/** ISO 3166-1 alpha-2 codes for Google Places `components=country:xx` biasing. */
const COUNTRY_ISO: Record<string, string> = {
  Ireland: 'ie',
  'Northern Ireland': 'gb',
  UK: 'gb',
  Germany: 'de',
  France: 'fr',
  Spain: 'es',
  Italy: 'it',
  Netherlands: 'nl',
  Belgium: 'be',
  Switzerland: 'ch',
  Austria: 'at',
  Poland: 'pl',
  Portugal: 'pt',
  Greece: 'gr',
  Sweden: 'se',
  Norway: 'no',
  Denmark: 'dk',
  Finland: 'fi',
  'Czech Republic': 'cz',
  Romania: 'ro',
  Hungary: 'hu',
  Bulgaria: 'bg',
  Croatia: 'hr',
  Serbia: 'rs',
  Slovakia: 'sk',
  Slovenia: 'si',
  Lithuania: 'lt',
  Latvia: 'lv',
  Estonia: 'ee',
  Luxembourg: 'lu',
  Malta: 'mt',
  Cyprus: 'cy',
  Iceland: 'is',
  Ukraine: 'ua',
  Belarus: 'by',
  Moldova: 'md',
  Albania: 'al',
  'North Macedonia': 'mk',
  'Bosnia and Herzegovina': 'ba',
  Montenegro: 'me',
  Kosovo: 'xk',
  Monaco: 'mc',
  Liechtenstein: 'li',
  Andorra: 'ad',
  'San Marino': 'sm',
  'Vatican City': 'va',
  Turkey: 'tr',
  USA: 'us',
  'United States': 'us',
  Canada: 'ca',
  Mexico: 'mx',
  Brazil: 'br',
  Argentina: 'ar',
  Chile: 'cl',
  Colombia: 'co',
  Peru: 'pe',
  Venezuela: 've',
  Ecuador: 'ec',
  Guatemala: 'gt',
  Cuba: 'cu',
  Haiti: 'ht',
  'Dominican Republic': 'do',
  Honduras: 'hn',
  'El Salvador': 'sv',
  Nicaragua: 'ni',
  'Costa Rica': 'cr',
  Panama: 'pa',
  Uruguay: 'uy',
  Paraguay: 'py',
  Bolivia: 'bo',
  Jamaica: 'jm',
  'Trinidad and Tobago': 'tt',
  Bahamas: 'bs',
  Barbados: 'bb',
  Belize: 'bz',
  Guyana: 'gy',
  Suriname: 'sr',
  'French Guiana': 'gf',
  China: 'cn',
  India: 'in',
  Japan: 'jp',
  Russia: 'ru',
  Indonesia: 'id',
  Pakistan: 'pk',
  Bangladesh: 'bd',
  Philippines: 'ph',
  Vietnam: 'vn',
  Thailand: 'th',
  Myanmar: 'mm',
  'South Korea': 'kr',
  'North Korea': 'kp',
  Malaysia: 'my',
  Afghanistan: 'af',
  Iraq: 'iq',
  'Saudi Arabia': 'sa',
  Uzbekistan: 'uz',
  Yemen: 'ye',
  Nepal: 'np',
  'Sri Lanka': 'lk',
  Kazakhstan: 'kz',
  Cambodia: 'kh',
  Jordan: 'jo',
  Azerbaijan: 'az',
  'United Arab Emirates': 'ae',
  Tajikistan: 'tj',
  Israel: 'il',
  Laos: 'la',
  Lebanon: 'lb',
  Kyrgyzstan: 'kg',
  Turkmenistan: 'tm',
  Singapore: 'sg',
  Oman: 'om',
  Palestine: 'ps',
  Kuwait: 'kw',
  Georgia: 'ge',
  Mongolia: 'mn',
  Armenia: 'am',
  Qatar: 'qa',
  Bahrain: 'bh',
  'Timor-Leste': 'tl',
  Bhutan: 'bt',
  Maldives: 'mv',
  Brunei: 'bn',
  Iran: 'ir',
  Syria: 'sy',
  Nigeria: 'ng',
  Ethiopia: 'et',
  Egypt: 'eg',
  'South Africa': 'za',
  Kenya: 'ke',
  Uganda: 'ug',
  Tanzania: 'tz',
  Algeria: 'dz',
  Sudan: 'sd',
  Morocco: 'ma',
  Angola: 'ao',
  Mozambique: 'mz',
  Ghana: 'gh',
  Madagascar: 'mg',
  Cameroon: 'cm',
  'Ivory Coast': 'ci',
  Niger: 'ne',
  'Burkina Faso': 'bf',
  Mali: 'ml',
  Malawi: 'mw',
  Zambia: 'zm',
  Senegal: 'sn',
  Chad: 'td',
  Somalia: 'so',
  Zimbabwe: 'zw',
  Guinea: 'gn',
  Rwanda: 'rw',
  Benin: 'bj',
  Tunisia: 'tn',
  Burundi: 'bi',
  'South Sudan': 'ss',
  Togo: 'tg',
  'Sierra Leone': 'sl',
  Libya: 'ly',
  Eritrea: 'er',
  'Central African Republic': 'cf',
  Liberia: 'lr',
  Mauritania: 'mr',
  Namibia: 'na',
  Botswana: 'bw',
  Gambia: 'gm',
  Gabon: 'ga',
  Lesotho: 'ls',
  'Guinea-Bissau': 'gw',
  'Equatorial Guinea': 'gq',
  Mauritius: 'mu',
  Eswatini: 'sz',
  Djibouti: 'dj',
  Comoros: 'km',
  'Cape Verde': 'cv',
  'São Tomé and Príncipe': 'st',
  Seychelles: 'sc',
  Australia: 'au',
  'New Zealand': 'nz',
  'Papua New Guinea': 'pg',
  Fiji: 'fj',
  'Solomon Islands': 'sb',
  Vanuatu: 'vu',
  'New Caledonia': 'nc',
  'French Polynesia': 'pf',
  Samoa: 'ws',
  Guam: 'gu',
  Kiribati: 'ki',
  Micronesia: 'fm',
  Tonga: 'to',
  'Marshall Islands': 'mh',
  Palau: 'pw',
  'American Samoa': 'as',
  'Northern Mariana Islands': 'mp',
  'Cook Islands': 'ck',
  Tuvalu: 'tv',
  'Wallis and Futuna': 'wf',
  Nauru: 'nr',
  Niue: 'nu',
  Tokelau: 'tk',
  'Pitcairn Islands': 'pn',
};

export function getCountryIsoCode(countryName: string): string {
  const trimmed = countryName.trim();
  if (!trimmed) return '';
  if (COUNTRY_ISO[trimmed]) return COUNTRY_ISO[trimmed];
  const lower = trimmed.toLowerCase();
  const key = Object.keys(COUNTRY_ISO).find((k) => k.toLowerCase() === lower);
  return key ? COUNTRY_ISO[key] : '';
}
