export type TextStoryTemplateSize = 'small' | 'medium' | 'large';

export interface TextStoryTemplate {
  id: string;
  name: string;
  background: string; // CSS color or gradient string
  textColor: string; // CSS color
  textSize: TextStoryTemplateSize;
  fontFamily: string;
}

/** Plain system UI sans-serif for every template (no cursive, serif, mono, or display fonts). */
export const TEXT_STORY_TEMPLATE_FONT =
  'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif';

export const TEXT_STORY_TEMPLATES: TextStoryTemplate[] = [
  // Blues, golds & jewel tones — listed first in create template picker
  {
    id: 'broadcast-blue',
    name: 'Broadcast',
    background: 'linear-gradient(165deg, #2563eb 0%, #1d4ed8 38%, #1e3a8a 72%, #172554 100%)',
    textColor: '#ffffff',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'cobalt',
    name: 'Cobalt',
    background: '#1e40af',
    textColor: '#f1f5f9',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'sapphire',
    name: 'Sapphire',
    background: 'linear-gradient(180deg, #1e3a8a 0%, #312e81 55%, #1e1b4b 100%)',
    textColor: '#e0e7ff',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'gold-luxe',
    name: 'Luxe Gold',
    background: 'linear-gradient(135deg, #713f12 0%, #b45309 25%, #ca8a04 55%, #eab308 78%, #a16207 100%)',
    textColor: '#fefce8',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'champagne',
    name: 'Champagne',
    background: 'linear-gradient(135deg, #fef9c3, #fde68a, #fcd34d)',
    textColor: '#422006',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'antique-gold',
    name: 'Antique',
    background: 'linear-gradient(145deg, #422006 0%, #78350f 45%, #92400e 100%)',
    textColor: '#fef3c7',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'bronze',
    name: 'Bronze',
    background: 'linear-gradient(135deg, #431407, #7c2d12, #b45309)',
    textColor: '#fed7aa',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'midnight-gold',
    name: 'Midnight & Gold',
    background: 'radial-gradient(ellipse at top right, #422006 0%, #0f172a 55%, #020617 100%)',
    textColor: '#fcd34d',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'minimal-white',
    name: 'Minimal',
    background: '#ffffff',
    textColor: '#111827',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'night-mode',
    name: 'Night',
    background: 'radial-gradient(circle at top, #111827, #020617)',
    textColor: '#f9fafb',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'gazetteer-gradient',
    name: 'Gazetteer',
    background: 'linear-gradient(135deg,#3b82f6,#a855f7)',
    textColor: '#ffffff',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'paper-map',
    name: 'Map',
    background: 'linear-gradient(135deg,#4b5563,#111827)',
    textColor: '#f9fafb',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'polaroid',
    name: 'Polaroid',
    background: '#e5e7eb',
    textColor: '#111827',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'postcard',
    name: 'Postcard',
    background: '#f3f4f6',
    textColor: '#111827',
    textSize: 'small',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'bold-color',
    name: 'Bold',
    background: '#f97316',
    textColor: '#ffffff',
    textSize: 'large',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'highlight',
    name: 'Highlight',
    background: '#fef9c3',
    textColor: '#111827',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'sticky-note',
    name: 'Note',
    background: '#fde68a',
    textColor: '#111827',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'chat-bubble',
    name: 'Chat',
    background: '#e0f2fe',
    textColor: '#0f172a',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'elegant-script',
    name: 'Script',
    background: 'linear-gradient(135deg,#0f172a,#1e293b)',
    textColor: '#f9fafb',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'mono-terminal',
    name: 'Mono',
    background: '#020617',
    textColor: '#e5e7eb',
    textSize: 'small',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'playful-bubble',
    name: 'Bubble',
    background: 'linear-gradient(135deg,#f97316,#ec4899)',
    textColor: '#ffffff',
    textSize: 'large',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'newspaper',
    name: 'News',
    background: '#f5f5f4',
    textColor: '#111827',
    textSize: 'small',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'marker',
    name: 'Marker',
    background: '#111827',
    textColor: '#facc15',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'soft-pastel',
    name: 'Pastel',
    background: 'linear-gradient(135deg,#fee2e2,#e0f2fe)',
    textColor: '#111827',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'headline',
    name: 'Headline',
    background: '#111827',
    textColor: '#f9fafb',
    textSize: 'large',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'neon',
    name: 'Neon',
    background: 'radial-gradient(circle at top,#22d3ee,#4c1d95)',
    textColor: '#f9fafb',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  // More styles
  {
    id: 'sunset',
    name: 'Sunset',
    background: 'linear-gradient(135deg,#f97316,#dc2626,#7c2d12)',
    textColor: '#fef3c7',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'ocean',
    name: 'Ocean',
    background: 'linear-gradient(180deg,#0e7490,#155e75,#0f172a)',
    textColor: '#e0f2fe',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'forest',
    name: 'Forest',
    background: 'linear-gradient(135deg,#14532d,#166534,#15803d)',
    textColor: '#dcfce7',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'lavender',
    name: 'Lavender',
    background: 'linear-gradient(135deg,#7c3aed,#a78bfa,#c4b5fd)',
    textColor: '#1e1b4b',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'mint',
    name: 'Mint',
    background: 'linear-gradient(135deg,#ccfbf1,#99f6e4,#5eead4)',
    textColor: '#134e4a',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'candy',
    name: 'Candy',
    background: 'linear-gradient(135deg,#fbcfe8,#f9a8d4,#ec4899)',
    textColor: '#831843',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'slate',
    name: 'Slate',
    background: 'linear-gradient(135deg,#475569,#334155,#1e293b)',
    textColor: '#f1f5f9',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'amber',
    name: 'Amber',
    background: 'linear-gradient(135deg,#fef3c7,#fde68a,#fcd34d)',
    textColor: '#78350f',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'typewriter',
    name: 'Typewriter',
    background: '#1c1917',
    textColor: '#d6d3d1',
    textSize: 'small',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'retro',
    name: 'Retro',
    background: 'linear-gradient(135deg,#78716c,#57534e,#44403c)',
    textColor: '#fafaf9',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'berry',
    name: 'Berry',
    background: 'linear-gradient(135deg,#881337,#9f1239,#be123c)',
    textColor: '#fecdd3',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'sky',
    name: 'Sky',
    background: 'linear-gradient(180deg,#0ea5e9,#38bdf8,#7dd3fc)',
    textColor: '#0c4a6e',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'cream',
    name: 'Cream',
    background: '#fefce8',
    textColor: '#422006',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'ink',
    name: 'Ink',
    background: '#0c0a09',
    textColor: '#fafaf9',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },

  // Instagram Stories “Create”–style canvases (preset gradient moods, story-sized contrast)
  {
    id: 'ig-blush-dawn',
    name: 'Story · Blush',
    background: 'linear-gradient(180deg, #fff1f2 0%, #fce7f3 42%, #ede9fe 100%)',
    textColor: '#4c1d95',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'ig-peach-glow',
    name: 'Story · Peach',
    background: 'linear-gradient(145deg, #fff7ed 0%, #fed7aa 38%, #fb923c 72%, #f97316 100%)',
    textColor: '#431407',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'ig-sea-glass',
    name: 'Story · Aqua',
    background: 'linear-gradient(165deg, #0f766e 0%, #14b8a6 45%, #5eead4 88%)',
    textColor: '#ecfdf5',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'ig-purple-haze',
    name: 'Story · Violet',
    background: 'linear-gradient(135deg, #4c1d95 0%, #7c3aed 38%, #c026d3 78%, #db2777 100%)',
    textColor: '#faf5ff',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'ig-blue-hour',
    name: 'Story · Blue',
    background: 'linear-gradient(160deg, #075985 0%, #2563eb 48%, #4338ca 100%)',
    textColor: '#eff6ff',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'ig-morning-mist',
    name: 'Story · Mist',
    background: 'linear-gradient(180deg, #f8fafc 0%, #e2e8f0 55%, #cbd5e1 100%)',
    textColor: '#0f172a',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'ig-sunset-strip',
    name: 'Story · Sunset',
    background: 'linear-gradient(135deg, #fcd34d 0%, #fb923c 32%, #f472b6 68%, #e11d48 100%)',
    textColor: '#fffbeb',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'ig-neon-night',
    name: 'Story · Dark',
    background: 'linear-gradient(165deg, #09090b 0%, #18181b 45%, #27272a 100%)',
    textColor: '#fafafa',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'ig-matcha',
    name: 'Story · Matcha',
    background: 'linear-gradient(135deg, #ecfccb 0%, #bef264 38%, #4ade80 85%)',
    textColor: '#14532d',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'ig-lilac-dream',
    name: 'Story · Lilac',
    background: 'linear-gradient(180deg, #faf5ff 0%, #e9d5ff 50%, #d8b4fe 100%)',
    textColor: '#4c1d95',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'ig-cotton-candy',
    name: 'Story · Candy',
    background: 'linear-gradient(135deg, #fbcfe8 0%, #f5d0fe 40%, #93c5fd 90%)',
    textColor: '#831843',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'ig-deep-teal',
    name: 'Story · Teal',
    background: 'linear-gradient(180deg, #022c22 0%, #115e59 48%, #134e4a 100%)',
    textColor: '#ccfbf1',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'ig-warm-vanilla',
    name: 'Story · Vanilla',
    background: 'linear-gradient(135deg, #fffbeb 0%, #fef3c7 55%, #fde68a 100%)',
    textColor: '#713f12',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'ig-cherry-pop',
    name: 'Story · Cherry',
    background: 'linear-gradient(135deg, #9f1239 0%, #e11d48 45%, #fb7185 100%)',
    textColor: '#fff1f2',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'ig-arctic-ice',
    name: 'Story · Ice',
    background: 'linear-gradient(165deg, #f0fdfa 0%, #cffafe 42%, #67e8f9 95%)',
    textColor: '#164e63',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'ig-twilight-flare',
    name: 'Story · Twilight',
    background: 'linear-gradient(135deg, #312e81 0%, #6d28d9 42%, #ea580c 92%)',
    textColor: '#fefce8',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'ig-monochrome',
    name: 'Story · Mono',
    background: 'linear-gradient(180deg, #71717a 0%, #52525b 50%, #3f3f46 100%)',
    textColor: '#fafafa',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'ig-paper-bright',
    name: 'Story · Paper',
    background: 'linear-gradient(180deg, #ffffff 0%, #fafafa 55%, #f4f4f5 100%)',
    textColor: '#18181b',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },

  // Lightweight story-specific templates (24hr stories)
  {
    id: 'neon-frame',
    name: 'Neon Glow',
    background:
      'radial-gradient(circle at top, rgba(56,189,248,0.22), rgba(15,23,42,1))',
    textColor: '#f9fafb',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'gradient-motion',
    name: 'Gradient Motion',
    background:
      'linear-gradient(135deg,#22c55e,#06b6d4,#6366f1,#ec4899)',
    textColor: '#f9fafb',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
  {
    id: 'glass-shimmer',
    name: 'Glass Shimmer',
    background:
      'linear-gradient(135deg,rgba(15,23,42,0.95),rgba(15,23,42,0.85))',
    textColor: '#e5e7eb',
    textSize: 'medium',
    fontFamily: TEXT_STORY_TEMPLATE_FONT,
  },
];

