export type TextStoryTemplateSize = 'small' | 'medium' | 'large';

export interface TextStoryTemplate {
  id: string;
  name: string;
  background: string; // CSS color or gradient string
  textColor: string; // CSS color
  textSize: TextStoryTemplateSize;
  fontFamily: string; // CSS font-family string
}

export const TEXT_STORY_TEMPLATES: TextStoryTemplate[] = [
  {
    id: 'minimal-white',
    name: 'Minimal',
    background: '#ffffff',
    textColor: '#111827',
    textSize: 'medium',
    fontFamily: 'Georgia, \"Times New Roman\", serif',
  },
  {
    id: 'night-mode',
    name: 'Night',
    background: 'radial-gradient(circle at top, #111827, #020617)',
    textColor: '#f9fafb',
    textSize: 'medium',
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif',
  },
  {
    id: 'gazetteer-gradient',
    name: 'Gazetteer',
    background: 'linear-gradient(135deg,#3b82f6,#a855f7)',
    textColor: '#ffffff',
    textSize: 'medium',
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif',
  },
  {
    id: 'paper-map',
    name: 'Map',
    background: 'linear-gradient(135deg,#4b5563,#111827)',
    textColor: '#f9fafb',
    textSize: 'medium',
    fontFamily: 'Georgia, \"Times New Roman\", serif',
  },
  {
    id: 'polaroid',
    name: 'Polaroid',
    background: '#e5e7eb',
    textColor: '#111827',
    textSize: 'medium',
    fontFamily: '\"Times New Roman\", Georgia, serif',
  },
  {
    id: 'postcard',
    name: 'Postcard',
    background: '#f3f4f6',
    textColor: '#111827',
    textSize: 'small',
    fontFamily: 'Georgia, \"Times New Roman\", serif',
  },
  {
    id: 'bold-color',
    name: 'Bold',
    background: '#f97316',
    textColor: '#ffffff',
    textSize: 'large',
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif',
  },
  {
    id: 'highlight',
    name: 'Highlight',
    background: '#fef9c3',
    textColor: '#111827',
    textSize: 'medium',
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif',
  },
  {
    id: 'sticky-note',
    name: 'Note',
    background: '#fde68a',
    textColor: '#111827',
    textSize: 'medium',
    fontFamily: '\"Comic Sans MS\", \"Comic Sans\", cursive',
  },
  {
    id: 'chat-bubble',
    name: 'Chat',
    background: '#e0f2fe',
    textColor: '#0f172a',
    textSize: 'medium',
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif',
  },
  // Extra templates with different font styles
  {
    id: 'elegant-script',
    name: 'Script',
    background: 'linear-gradient(135deg,#0f172a,#1e293b)',
    textColor: '#f9fafb',
    textSize: 'medium',
    fontFamily: '\"Palatino Linotype\",\"Book Antiqua\",Palatino,serif',
  },
  {
    id: 'mono-terminal',
    name: 'Mono',
    background: '#020617',
    textColor: '#e5e7eb',
    textSize: 'small',
    fontFamily: '\"Courier New\",Courier,monospace',
  },
  {
    id: 'playful-bubble',
    name: 'Bubble',
    background: 'linear-gradient(135deg,#f97316,#ec4899)',
    textColor: '#ffffff',
    textSize: 'large',
    fontFamily: '\"Trebuchet MS\",\"Lucida Grande\",\"Lucida Sans Unicode\",sans-serif',
  },
  {
    id: 'newspaper',
    name: 'News',
    background: '#f5f5f4',
    textColor: '#111827',
    textSize: 'small',
    fontFamily: '\"Times New Roman\",Georgia,serif',
  },
  {
    id: 'marker',
    name: 'Marker',
    background: '#111827',
    textColor: '#facc15',
    textSize: 'medium',
    fontFamily: '\"Comic Sans MS\",\"Comic Sans\",cursive',
  },
  {
    id: 'soft-pastel',
    name: 'Pastel',
    background: 'linear-gradient(135deg,#fee2e2,#e0f2fe)',
    textColor: '#111827',
    textSize: 'medium',
    fontFamily: '\"Verdana\",\"Geneva\",sans-serif',
  },
  {
    id: 'headline',
    name: 'Headline',
    background: '#111827',
    textColor: '#f9fafb',
    textSize: 'large',
    fontFamily: '\"Impact\",\"Haettenschweiler\",\"Arial Narrow Bold\",sans-serif',
  },
  {
    id: 'neon',
    name: 'Neon',
    background: 'radial-gradient(circle at top,#22d3ee,#4c1d95)',
    textColor: '#f9fafb',
    textSize: 'medium',
    fontFamily: '\"Gill Sans\",\"Gill Sans MT\",Calibri,\"Trebuchet MS\",sans-serif',
  },
  // More styles
  {
    id: 'sunset',
    name: 'Sunset',
    background: 'linear-gradient(135deg,#f97316,#dc2626,#7c2d12)',
    textColor: '#fef3c7',
    textSize: 'medium',
    fontFamily: 'Georgia,\"Times New Roman\",serif',
  },
  {
    id: 'ocean',
    name: 'Ocean',
    background: 'linear-gradient(180deg,#0e7490,#155e75,#0f172a)',
    textColor: '#e0f2fe',
    textSize: 'medium',
    fontFamily: 'system-ui,-apple-system,BlinkMacSystemFont,\"Segoe UI\",sans-serif',
  },
  {
    id: 'forest',
    name: 'Forest',
    background: 'linear-gradient(135deg,#14532d,#166534,#15803d)',
    textColor: '#dcfce7',
    textSize: 'medium',
    fontFamily: '\"Georgia\",\"Times New Roman\",serif',
  },
  {
    id: 'lavender',
    name: 'Lavender',
    background: 'linear-gradient(135deg,#7c3aed,#a78bfa,#c4b5fd)',
    textColor: '#1e1b4b',
    textSize: 'medium',
    fontFamily: '\"Palatino Linotype\",Palatino,serif',
  },
  {
    id: 'mint',
    name: 'Mint',
    background: 'linear-gradient(135deg,#ccfbf1,#99f6e4,#5eead4)',
    textColor: '#134e4a',
    textSize: 'medium',
    fontFamily: 'system-ui,-apple-system,BlinkMacSystemFont,\"Segoe UI\",sans-serif',
  },
  {
    id: 'candy',
    name: 'Candy',
    background: 'linear-gradient(135deg,#fbcfe8,#f9a8d4,#ec4899)',
    textColor: '#831843',
    textSize: 'medium',
    fontFamily: '\"Comic Sans MS\",\"Comic Sans\",cursive',
  },
  {
    id: 'slate',
    name: 'Slate',
    background: 'linear-gradient(135deg,#475569,#334155,#1e293b)',
    textColor: '#f1f5f9',
    textSize: 'medium',
    fontFamily: '\"Segoe UI\",system-ui,sans-serif',
  },
  {
    id: 'amber',
    name: 'Amber',
    background: 'linear-gradient(135deg,#fef3c7,#fde68a,#fcd34d)',
    textColor: '#78350f',
    textSize: 'medium',
    fontFamily: 'Georgia,\"Times New Roman\",serif',
  },
  {
    id: 'typewriter',
    name: 'Typewriter',
    background: '#1c1917',
    textColor: '#d6d3d1',
    textSize: 'small',
    fontFamily: '\"Courier New\",Courier,monospace',
  },
  {
    id: 'retro',
    name: 'Retro',
    background: 'linear-gradient(135deg,#78716c,#57534e,#44403c)',
    textColor: '#fafaf9',
    textSize: 'medium',
    fontFamily: '\"American Typewriter\",\"Lucida Console\",monospace',
  },
  {
    id: 'berry',
    name: 'Berry',
    background: 'linear-gradient(135deg,#881337,#9f1239,#be123c)',
    textColor: '#fecdd3',
    textSize: 'medium',
    fontFamily: 'Georgia,\"Times New Roman\",serif',
  },
  {
    id: 'sky',
    name: 'Sky',
    background: 'linear-gradient(180deg,#0ea5e9,#38bdf8,#7dd3fc)',
    textColor: '#0c4a6e',
    textSize: 'medium',
    fontFamily: 'system-ui,-apple-system,BlinkMacSystemFont,\"Segoe UI\",sans-serif',
  },
  {
    id: 'cream',
    name: 'Cream',
    background: '#fefce8',
    textColor: '#422006',
    textSize: 'medium',
    fontFamily: '\"Times New Roman\",Georgia,serif',
  },
  {
    id: 'ink',
    name: 'Ink',
    background: '#0c0a09',
    textColor: '#fafaf9',
    textSize: 'medium',
    fontFamily: '\"Palatino Linotype\",\"Book Antiqua\",Palatino,serif',
  },
];

