<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('music', function (Blueprint $table) {
            $table->id();
            $table->string('title');
            $table->string('artist')->nullable();
            $table->string('genre')->nullable(); // pop, rock, electronic, hip-hop, jazz, classical
            $table->string('mood')->nullable(); // happy, energetic, calm, dramatic, romantic, upbeat
            $table->integer('duration')->nullable(); // Duration in seconds
            $table->string('url'); // Storage path/URL to audio file
            $table->string('thumbnail_url')->nullable(); // Optional thumbnail/album art
            $table->integer('usage_count')->default(0); // Track how many times used
            $table->boolean('is_ai_generated')->default(false); // Whether generated by AI
            $table->string('ai_service')->nullable(); // Which AI service (suno, mubert, etc.)
            $table->json('metadata')->nullable(); // Additional metadata (BPM, key, etc.)
            $table->boolean('is_active')->default(true); // Enable/disable tracks
            $table->timestamps();
            
            // Indexes for faster queries
            $table->index('genre');
            $table->index('mood');
            $table->index('is_ai_generated');
            $table->index('is_active');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('music');
    }
};





















